name: 'Setup system'

inputs:
  system-name:
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true
      # Cache across the same system
      with:
        key: ${{ inputs.system-name }}-docker-cache-{hash}
        restore-keys: |
          ${{ inputs.system-name }}-docker-cache-

    - name: Add write permission to directories
      shell: bash
      run: |
        find . -type d -exec chmod 777 {} \;

    - name: Setup ${{ inputs.system-name }} system
      shell: bash
      run: |
        make sys_${{ inputs.system-name }}
